// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kosmapeqytbvmuobfgsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvc21hcGVxeXRidm11b2JmZ3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDY4NjYsImV4cCI6MjA2NzI4Mjg2Nn0.uGzraiKW8dIswL2Uq_74kFOKEsZTqlQlCunTCvhXM44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});